### ISSUE TITLE
How to build with native cmake tools

### ISSUE THREAD

**Issue by LishaUnfoolish** [bazelbuild/rules_foreign_cc#1085]
How should I configure it to use my local cmake tool instead of downloading it online via built_toolchains?
My downloads often fail because of the internet.
I hope I can build it offline,the error message is as follows:
`
INFO: Build options --compilation_mode and --compiler have changed, discarding analysis cache.
INFO: Analyzed 140 targets (60 packages loaded, 1170 targets configured).
INFO: Found 140 targets...
INFO: Elapsed time: 0.442s, Critical Path: 0.01s
INFO: 143 processes: 143 internal.
INFO: Build options --compilation_mode and --compiler have changed, discarding analysis cache.
INFO: Repository cmake-3.23.2-linux-x86_64 instantiated at:
  /project/WORKSPACE:131:30: in <toplevel>
  /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/rules_foreign_cc/foreign_cc/repositories.bzl:74:28: in rules_foreign_cc_dependencies
  /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/rules_foreign_cc/toolchains/prebuilt_toolchains.bzl:65:22: in prebuilt_toolchains
  /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/rules_foreign_cc/toolchains/prebuilt_toolchains.bzl:85:14: in _cmake_toolchains
  /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
WARNING: Download from https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: objects.githubusercontent.com
ERROR: An error occurred during the fetch of repository 'cmake-3.23.2-linux-x86_64':
   Traceback (most recent call last):
        File "/home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz] to /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/cmake-3.23.2-linux-x86_64/temp756376511170669074/cmake-3.23.2-linux-x86_64.tar.gz: Unknown host: objects.githubusercontent.com
ERROR: /project/WORKSPACE:131:30: fetching http_archive rule //external:cmake-3.23.2-linux-x86_64: Traceback (most recent call last):
        File "/home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz] to /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/cmake-3.23.2-linux-x86_64/temp756376511170669074/cmake-3.23.2-linux-x86_64.tar.gz: Unknown host: objects.githubusercontent.com
ERROR: /project/third_party/fmt/BUILD:14:6: //third_party/fmt:fmt depends on @cmake-3.23.2-linux-x86_64//:cmake_tool in repository @cmake-3.23.2-linux-x86_64 which failed to fetch. no such package '@cmake-3.23.2-linux-x86_64//': java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz] to /home/xxx/.cache/bazel/_bazel_xxx/e1c602535fcdbe4ddc2af9250bb35649/external/cmake-3.23.2-linux-x86_64/temp756376511170669074/cmake-3.23.2-linux-x86_64.tar.gz: Unknown host: objects.githubusercontent.com
ERROR: Analysis of target '//third_party/fmt:fmt' failed; build aborted: Analysis failed
INFO: Elapsed time: 213.591s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (65 packages loaded, 1228 targets configured)
    Fetching https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz; 2,096,800B 188s
build failed`

**Comment by LishaUnfoolish** [comment]
The problem is solved.
