### ISSUE TITLE
Error: apple_binary has to declare 'j2objc' as a required fragment in order to access it


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_foreign_cc#1174]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3666#018dbf1b-3cbe-4c61-9a9c-16e688908a53

 Platform: MacOS

 Logs: 
```
ERROR: /private/var/tmp/_bazel_buildkite/11c12dd531e304ce9b0996a76e1be238/external/rules_foreign_cc_examples_third_party/cares/BUILD.bazel:19:13: in apple_binary rule @@rules_foreign_cc_examples_third_party//cares:ios_binary:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/11c12dd531e304ce9b0996a76e1be238/external/build_bazel_rules_apple/apple/apple_binary.bzl", line 87, column 65, in _apple_binary_impl
		link_result = linking_support.register_binary_linking_action(
	File "/private/var/tmp/_bazel_buildkite/11c12dd531e304ce9b0996a76e1be238/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 243, column 58, in _register_binary_linking_action
		linking_outputs = apple_common.link_multi_arch_binary(
	File "/virtual_builtins_bzl/common/objc/linking_support.bzl", line 265, column 86, in _link_multi_arch_binary
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 807, column 62, in _register_configuration_specific_link_actions
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 579, column 26, in _register_j2objc_dead_code_removal_actions
Error: apple_binary has to declare 'j2objc' as a required fragment in order to access it. Please update the 'fragments' argument of the rule definition (for example: fragments = ["j2objc"])
(03:05:03) ERROR: /private/var/tmp/_bazel_buildkite/11c12dd531e304ce9b0996a76e1be238/external/rules_foreign_cc_examples_third_party/cares/BUILD.bazel:19:13: Analysis of target '@@rules_foreign_cc_examples_third_party//cares:ios_binary' failed
(03:05:03) ERROR: Analysis of target '@@rules_foreign_cc_examples_third_party//cares:test_c_ares_ios' failed; build aborted: Analysis failed
(03:05:03) INFO: Elapsed time: 25.592s, Critical Path: 0.72s
(03:05:03) INFO: 180 processes: 180 internal.
(03:05:03) ERROR: Build did NOT complete successfully
(03:05:03) FAILED:
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_foreign_cc
git reset 15da39ad4d18135a321cf0bc66df706373748138  --hard
export USE_BAZEL_VERSION=38c1d5d27061481b1a688abb37c6f1dd8b288c26
bazel build //... //:third_party_examples_macos_tests -//cmake_android/... -@rules_foreign_cc_examples_third_party//curl:curl_test -@rules_foreign_cc_examples_third_party//openssl:openssl_test 
 ``` 
 CC Greenteam @fweikert

**Comment by sgowroji** [comment]
Hi @jsharpe, Rules\_foreign\_cc is still failing in downstream CI [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3695#018e0734-d507-4ff8-a73e-f59f7e30bf1d.](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3695#018e0734-d507-4ff8-a73e-f59f7e30bf1d.) Can you take a look, if there are any more declarations of 'j2objc' which are missed. Thanks!
