### ISSUE TITLE
cmake_external breaks on remote execution build

### ISSUE THREAD

**Issue by pweaver** [bazelbuild/rules_foreign_cc#119]
On a remote execution build from OSX to Linux the WORKSPACE setup depends on rctx.os which breaks when the actions are run in a Linux environment.

**Comment by nlopezgi** [comment]
This kind of use of repository rules is not supported on remote execution. Please see https://docs.bazel.build/versions/master/remote-execution-rules.html#managing-configure-style-workspace-rules for an explanation why and advice on how to fix. Please also reach out to me if you want to get these rules working with remote execution and have more questions about the process.

**Comment by bbarnes52** [comment]
Hi Nicholas! We are just starting the process of getting remote execution working and depend heavily on these rules. Just sent an email to the address listed on your GitHub profile. Thank you!

**Comment by irengrig** [comment]
Thank you for your feedback!
I have not experimented yet with using this rule on remote execution.
I think in general additional work is required to make this work.
You contribution is very welcome!

I will post my updates on the topic here.

**Comment by bbarnes52** [comment]
Quick update: I tried @nlopezgi recommendation of using the same docker image across environments, I was able to get it working for a toy example, but when I tried it on a simple `rules_foreign_cc` target, I received the following error, which seems to be related to the `cmake_external` rule implementation itself.

```
set_platform_env_vars
export EXT_BUILD_ROOT=$BUILD_PWD
export BUILD_TMPDIR=$...' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed: com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed with not retriable error: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid arguments: 
  "command.output_directories.parent_dir": Output directory bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas/bin is the child of output directory bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas
  "command.output_directories.file_with_parent_dir": Output file bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas/lib/libopenblas.a has a parent directory in OutputDirectories
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:286)
        at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:121)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:215)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:107)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:971)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:900)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:118)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:744)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:699)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:459)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid arguments: 
  "command.output_directories.parent_dir": Output directory bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas/bin is the child of output directory bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas
  "command.output_directories.file_with_parent_dir": Output file bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas/lib/libopenblas.a has a parent directory in OutputDirectories
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:557)
        at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$0(GrpcRemoteExecutor.java:149)
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:268)
        at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:121)
        at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:138)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$0(RemoteSpawnRunner.java:219)
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:268)
        ... 21 more
Target //third_party/cmake/openblas:openblas failed to build
```

**Comment by pweaver** [comment]
This is not my highest priority right now but I will probably put more work into getting this to work in the future.

**Comment by bbarnes52** [comment]
From Steven Bergsieker:

```
You cannot request both a directory and one of its descendants (either file or directory) as outputs. Just requesting the higher-level directory is sufficient. In this case, you are explicitly specifying all of 

bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas/bin
bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas
bazel-out/k8-fastbuild/genfiles/third_party/cmake/openblas/openblas/lib/libopenblas.a

// 1. any of the requested output directories is a parent of another requested output directory,
// 2. there are any duplicate directories in the list of requested output directories,
// 3.	there is an output directory that is specified as an output file too,
// 4. there is an output directory that is a parent of an output file.
// All of these checks are done based on the assumption that the list is already sorted as
// specified by the API.
```

I tried updating framework.bzl, but if I simply removed entries from `declared_outputs`, bazel threw an error saying there was no generating actions for certain files, and each of these files have a number of dependencies that I don't fully understand.

**Comment by pweaver** [comment]
Following up on this:
I managed to get opencv compiling with a custom toolchain with the following bugs for cross platform remote builds.
In framework.bzl
1) The shell utils need to select the correct script for the execution platform, not the host platform.
2) TMPDIR is set by the host so $BUILD_TEMPDIR might not exist. a mkdir -p helps.
3) cmake doesn't like relative paths to CC and CXX so adding  "path $EXT_BUILD_ROOT" fixed it.
4) cmake got the wrong path to AR so CMAKE_AR need to be set to AR

My fixes are still hacks and not ready for upstream but thoughts on how to fix here?

**Comment by irengrig** [comment]
Hi @pweaver @bbarnes52,

thank you for the information!

@bbarnes52 Yes, you are right. I missed that restriction. However, it fails only on remote execution. I am going to fix it later this week, but probably after BazelCon is over.

@pweaver Interesting! What toolchain do you mean?
1. Yes, definitely
2. ok I will check that
3. actually I have code attempting to replace relative paths with absolute, here: https://github.com/bazelbuild/rules_foreign_cc/blob/496509033573e1e1272a2272b995e9f9f8b3410c/tools/build_defs/cc_toolchain_util.bzl#L398
Since there are some toolchains using the relative path.
I think we should rather fix this place.
4. could you elaborate on that more exactly? Figuring these variables was not easy, so if to correct anything there, I should not make mistakes:)

I would be happy to have a look at the "hacks", I think it is a very good input for me.
Maybe your case can appear in the examples section?

As I see it, for the remote execution 
1) the WORKSPACE-level code should be updated for remote execution,
2) and CMake-make-ninja toolchain (toolchains?) should be created, similar to cc_toolchain.

**Comment by pweaver** [comment]
4). This is the failed output for the AR output. It looks like cmake expects absolute paths.
https://gist.github.com/pweaver/2bc6066bd90d3ba9a1c580483629eb5d

Also, note the `mkdir -p $TMPDIR`, `path $EXT_BUILD_ROOT` and I hard coded source external/foreign_cc_platform_utils/utils_unix.sh to get this to work this far.

If I set  "CMAKE_AR": "$EXT_BUILD_ROOT/tools/compilers/arm/gcc/arm-buildroot-linux-gnueabihf-ar", it builds without error.

This is a relatively complicated build which might be a good example. When I get a chance, I will extract it is simpler code that is not embedded in my repository.

**Comment by bbarnes52** [comment]
#125

**Comment by UebelAndre** [comment]
This may be related to https://github.com/bazelbuild/rules_foreign_cc/issues/673
