### ISSUE TITLE
QEMU build fails

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/rules_foreign_cc#128]
```
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")

licenses(["restricted"])  # GPL
exports_files(["LICENSE"])

filegroup(
	name = "all", 
	srcs = glob(["**"]), 
	visibility = ["//visibility:public"],
)

configure_make(
    name = "qemu",
    lib_source = ":all",
    configure_options = [
        "--enable-debug",
        "--target-list=x86_64-softmmu",
    ],
    out_bin_dir = "qemu",
    binaries = ["bin/qemu-system-x86_64"],
)
```
```
ERROR: qemu/BUILD:12:1: in configure_make rule //third_party/qemu:qemu: 
Traceback (most recent call last):
	File "qemu/BUILD", line 12
		configure_make(name = 'qemu')
	File ".cache/bazel/_bazel_kayab/21035df2e517bca2eb66693e8b13ea02/external/rules_foreign_cc/tools/build_defs/configure.bzl", line 29, in _configure_make
		cc_external_rule_impl(ctx, attrs)
	File "cache/bazel/_bazel_kayab/21035df2e517bca2eb66693e8b13ea02/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 192, in cc_external_rule_impl
		_define_outputs(ctx, attrs, lib_name)
	File ".cache/bazel/_bazel_kayab/21035df2e517bca2eb66693e8b13ea02/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 383, in _define_outputs
		_declare_out(ctx, lib_name, attrs.out_bin_dir, file)
	File ".cache/bazel/_bazel_kayab/21035df2e517bca2eb66693e8b13ea02/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 411, in _declare_out
		ctx.actions.declare_file("/".join([lib_name, dir.basename...]))
	File ".cache/bazel/_bazel_kayab/21035df2e517bca2eb66693e8b13ea02/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 411, in ctx.actions.declare_file
		"/".join([lib_name, dir.basename, file])
	File ".cache/bazel/_bazel_kayab/21035df2e517bca2eb66693e8b13ea02/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 411, in "/".join
		dir.basename
object of type 'string' has no field 'basename'
```

This error occurs with and without supplying `out_bin_dir`.

**Comment by irengrig** [comment]
Fixed by #131
