### ISSUE TITLE
Failure on `boost_build` compilations.

### ISSUE THREAD

**Issue by psigen** [bazelbuild/rules_foreign_cc#202]
The latest refactor to add `shell_toolchain` appears to be causing problems on `boost_build` compilations.  The following is the result of building using the current `master`.

**Source repo:** https://github.com/psigen/rules_foreign_cc_example

```bash
$ bazel build //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 6cd2a9d0-cdf7-49d6-84e5-45eb745e9225
INFO: Rule 'rules_foreign_cc' modified arguments {"shallow_since": "1547833417 +0100"}
ERROR: /home/pkv/Desktop/test_boost/BUILD.bazel:3:1: in boost_build rule //:boost_graph: 
Traceback (most recent call last):
	File "/home/pkv/Desktop/test_boost/BUILD.bazel", line 3
		boost_build(name = 'boost_graph')
	File "/home/pkv/.cache/bazel/_bazel_pkv/250043debb56c0706f5c2dfb2313c03e/external/rules_foreign_cc/tools/build_defs/boost_build.bzl", line 18, in _boost_build
		cc_external_rule_impl(ctx, attrs)
	File "/home/pkv/.cache/bazel/_bazel_pkv/250043debb56c0706f5c2dfb2313c03e/external/foreign_cc_impl/framework.bzl", line 204, in cc_external_rule_impl
		os_name(ctx)
	File "/home/pkv/.cache/bazel/_bazel_pkv/250043debb56c0706f5c2dfb2313c03e/external/rules_foreign_cc/tools/build_defs/shell_script_helper.bzl", line 38, in os_name
		call_shell(create_context(ctx), "os_name")
	File "/home/pkv/.cache/bazel/_bazel_pkv/250043debb56c0706f5c2dfb2313c03e/external/rules_foreign_cc/tools/build_defs/shell_script_helper.bzl", line 38, in call_shell
		create_context(ctx)
	File "/home/pkv/.cache/bazel/_bazel_pkv/250043debb56c0706f5c2dfb2313c03e/external/rules_foreign_cc/tools/build_defs/shell_toolchain/toolchains/access.bzl", line 8, in create_context
		struct(shell = ctx.toolchains["@rules_f..., ... {})
	File "/home/pkv/.cache/bazel/_bazel_pkv/250043debb56c0706f5c2dfb2313c03e/external/rules_foreign_cc/tools/build_defs/shell_toolchain/toolchains/access.bzl", line 9, in struct
		ctx.toolchains["@rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains:shell_commands"]
In boost_build rule //:boost_graph, toolchain type @rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains:shell_commands was requested but only types [] are configured
ERROR: Analysis of target '//:boost_graph' failed; build aborted: Analysis of target '//:boost_graph' failed; build aborted
INFO: Elapsed time: 11.768s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 61196 targets configured)
```

---

Platform: Ubuntu 16.04
```
$ bazel version
INFO: Invocation ID: 0751525e-de0a-4bfb-9b7e-e2e1fcb484c0
Build label: 0.21.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:44 2018 (1545224324)
Build timestamp: 1545224324
Build timestamp as int: 1545224324
```

**Comment by irengrig** [comment]
Thank you for reporting, will have a look now.

**Comment by psigen** [comment]
Thanks for the quick fix!

**Comment by irengrig** [comment]
Not at all:) I should have checked that better. The problem is boost example is too big to include into tests, by maybe I should consider that.
