### ISSUE TITLE
Example with pybind11 doesn't work

### ISSUE THREAD

**Issue by daniel-emotech** [bazelbuild/rules_foreign_cc#347]
Using bazel 1.0.0

WORKSPACE follows the example with the URL to the archive fixed.

From BUILD
```
cmake_external(
    name = "pybind11",
    cmake_options = ["-DPYBIND11_TEST=OFF"],
    headers_only = True,
    lib_source ="@pybind11//:all",
)
```

The error printout 
```
ERROR: /home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel:1:11: name 'name' is not defined
ERROR: /home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel:1:11: Traceback (most recent call last):
	File "/home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel", line 1
		filegroup((name - "all"), srcs = glob(["**"]..., ..."])
	File "/home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel", line 1, in filegroup
		name
name 'name' is not defined
ERROR: /home/olly/mmpa/lip-extractor/BUILD:72:1: no such target '@pybind11//:all': target 'all' not declared in package '' defined by /home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel and referenced by '//:pybind11'
ERROR: Analysis of target '//:pybind11' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.225s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 42 targets configured)
```

And this is the generated BUILD.bazel
`filegroup(name - "all", srcs = glob(["**"]), visibility = ["//visibility:public"])`

**Comment by daniel-emotech** [comment]
Just downgraded to 0.23.0 and it still doesn't work

```
INFO: SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip) = a2e43b2141cddce94999e26de8075031394ac11fb8075de8aa0b8e13905715ed
DEBUG: Rule 'rules_foreign_cc' modified arguments {"sha256": "a2e43b2141cddce94999e26de8075031394ac11fb8075de8aa0b8e13905715ed"}
INFO: SHA256 (https://mirror.bazel.build/github.com/pybind/pybind11/archive/v2.4.3.tar.gz) = 1eed57bc6863190e35637290f97a20c81cfe4d9090ac0a24f3bbf08f265eb71d
DEBUG: Rule 'pybind11' modified arguments {"sha256": "1eed57bc6863190e35637290f97a20c81cfe4d9090ac0a24f3bbf08f265eb71d"}
ERROR: /home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel:1:11: Traceback (most recent call last):
	File "/home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel", line 1
		filegroup((name - "all"), srcs = glob(["**"]..., ..."])
	File "/home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel", line 1, in filegroup
		name
name 'name' is not defined
ERROR: /home/olly/mmpa/lip-extractor/BUILD:72:1: no such target '@pybind11//:all': target 'all' not declared in package '' defined by /home/olly/.cache/bazel/_bazel_olly/605e98e155099b3c9e84a3f7548ad4a6/external/pybind11/BUILD.bazel and referenced by '//:pybind11'
ERROR: Analysis of target '//:pybind11' failed; build aborted: Analysis failed
INFO: Elapsed time: 7.040s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 72 targets configured)
```

**Comment by flichtenheld** [comment]
The problem here is the `name - "all"`, that needs to be `name = "all"`. But that doesn't seem to be a problem in the code as in Git.
