### ISSUE TITLE
Remove env_vars attribute of cmake()

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#666]
For some `cmake()` rule where I am passing both `env` and `env_vars`, and both are provided by a `select()`, I somehow get the error below:

```
ERROR: /build/lib/hdf/BUILD.bazel:54:10: in cmake rule //lib/hdf:hdf: 
Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_foreign_cc/foreign_cc/cmake.bzl", line 58, column 33, in _cmake_impl
                return cc_external_rule_impl(ctx, attrs)
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_foreign_cc/foreign_cc/private/framework.bzl", line 371, column 38, in cc_external_rule_impl
                ] + attrs.create_configure_script(ConfigureParameters(ctx = ctx, attrs = attrs, inputs = inputs)) + make_commands + postfix_script + [
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_foreign_cc/foreign_cc/cmake.bzl", line 122, column 43, in _create_configure_script
                configure_script = create_cmake_script(
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_foreign_cc/foreign_cc/private/cmake_script.bzl", line 50, column 48, in create_cmake_script
                params = _create_cache_entries_env_vars(toolchain_dict, user_cache, user_env)
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_foreign_cc/foreign_cc/private/cmake_script.bzl", line 170, column 22, in _create_cache_entries_env_vars
                _move_dict_values(toolchain_dict, user_env, _CMAKE_ENV_VARS_FOR_CROSSTOOL)
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_foreign_cc/foreign_cc/private/cmake_script.bzl", line 221, column 31, in _move_dict_values
                value = source.pop(key)
Error in pop: trying to mutate a frozen dict value
ERROR: Analysis of target '//lib/hdf:hdf' failed; build aborted: Analysis of target '//lib/hdf:hdf' failed
INFO: Elapsed time: 1.853s
INFO: 0 processes.
```

I'm not exactly sure yet what is causing this, nor do I have a minimum setup to reproduce the issue. I'll try to put together a minimal failing case.

**Comment by attilaolah** [comment]
Looks like this does not depend on `env`, and passing in any `env_vars` results in this error. But only when I pass `--cpu=wasm32` so something might be pulling in a `select()` somewhere.

**Comment by UebelAndre** [comment]
We should delete `env_vars`. I don't think it's needed now that there's `env` which is common to all rules vs `env_vars` which is specific to cmake. But I say that only having just discovered `env_vars` and spent 30 seconds reading where it's used 😅

**Comment by attilaolah** [comment]
Cool! Looks like merging everything into `env` and not specifying `env_vars` at all works just fine.

Let's remove `env_vars` then, not only is it confusing, but apparently it doesn't work either.

**Comment by attilaolah** [comment]
Also passing in only a single flag to `CFLAGS` doesn't seem to be picked up by CMake. However, it turns out I can pass in `CMAKE_C_FLAGS` through `cache_entries`, so now I have no need for the `env_vars`.

Good to remove it, once again :)

**Comment by attilaolah** [comment]
I don't use any of those. I think the combination of `autoconf_options` and `env` is enough to replace `autoconf_env_vars`, and so on for the rest.

The only thing that did not work for me when setting via `env` instead of e.g. `configure_env_vars`, is setting env vars that are passed in by the framework itself, e.g. `CFLAGS`, `LDFLAGS`, etc. Even if I set these in `env`, it seems like when calling `configure` these are passed in via the command line, and I don't think they were properly merged.

So maybe we should take extra care that the vars passed in on the command line to the `configure`, `autoconf`, `autogen` invocations are merged with the values passed in via `env`. (I think this could even be done at the sell level, e.g. `CFLAGS="${CFLAGS} additional cflags…"`, but could also be done in Starlark by the config script generator.)
